syntax = "proto3";

option java_multiple_files = true;
option java_package = "hse.api.proto.grpc";
option java_outer_classname = "PaymentsProto";

service PaymentsService {
  rpc CreateAccount(CreateAccountRequest) returns (CreateAccountResponse) {}
  rpc Deposit(DepositRequest) returns (DepositResponse) {}
  rpc GetBalance(GetBalanceRequest) returns (GetBalanceResponse) {}
}

message CreateAccountRequest {
  string user_id = 1;
}

message CreateAccountResponse {
  bool success = 1;
}

message DepositRequest {
  string user_id = 1;
  double amount = 2;
}

message DepositResponse {
  bool success = 1;
  double new_balance = 2;
}

message GetBalanceRequest {
  string user_id = 1;
}

message GetBalanceResponse {
  double balance = 1;
}